name: task
on:
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: one
        run: |
          wget https://use.fontawesome.com/releases/v6.2.0/fontawesome-free-6.2.0-web.zip
          unzip fontawesome-free-6.2.0-web.zip
          rm -rf assets/custom/css
          cp fontawesome-free-6.2.0-web/css assets/custom && cp fontawesome-free-6.2.0-web/webfonts assets/custom
          rm -rf fontawesome-free-6.2.0-web.zip
          rm -rf fontawesome-free-6.2.0-web
      - name: Commit
        run: |
          git config --global user.name 'github-actions[BOT]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -am "exc"
          git push
